services:
  kafka:
    image: apache/kafka:4.3.1
    container_name: kafka
    hostname: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://:19092,EXTERNAL://:9092,CONTROLLER://:29093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://${AUTOMATION_INTERNAL_IP}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1

      KAFKA_HEAP_OPTS: "-Xms384m -Xmx768m"
      CLUSTER_ID: ${KAFKA_CLUSTER_ID:-4L6g3nShT-eMCtK--X86sw}

    networks:
      - automation-network

  n8n:
    image: n8nio/n8n:2.22.6
    container_name: n8n
    restart: always
    environment:
      N8N_HOST: n8n.ittaeok.org
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      WEBHOOK_URL: https://n8n.ittaeok.org/
      N8N_EDITOR_BASE_URL: https://n8n.ittaeok.org/
      N8N_PROXY_HOPS: 1
      GENERIC_TIMEZONE: Asia/Seoul
      TZ: Asia/Seoul
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      NODE_OPTIONS: "--max-old-space-size=512"

    ports:
      - "5678:5678"

    volumes:
      - n8n_data:/home/node/.n8n

    networks:
      - automation-network

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: always
    depends_on:
      - n8n
    command:
      - caddy
      - reverse-proxy
      - --from
      - n8n.ittaeok.org
      - --to
      - n8n:5678
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - automation-network

  kafbat-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    container_name: kafbat-ui
    restart: always
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: ittaeok
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:19092
    ports:
      - "8081:8080"
    networks:
      - automation-network

volumes:
  n8n_data:
  caddy_data:
  caddy_config:

networks:
  automation-network:
    driver: bridge